"""Markdown formatter for COMPLIANCE.md output."""

from __future__ import annotations

from collections import defaultdict

from ..models import Result, RuleResult


def format_markdown(results: list[RuleResult]) -> str:
    """Format results as markdown suitable for COMPLIANCE.md."""
    lines = []

    # Header
    lines.append("# Compliance Report")
    lines.append("")
    lines.append("Auto-generated by `shadow-spec-check`. Do not edit manually.")
    lines.append("")

    # Summary
    pass_count = sum(1 for r in results if r.result == Result.PASS)
    dev_count = sum(1 for r in results if r.result == Result.DEVIATES)
    na_count = sum(1 for r in results if r.result == Result.NA)
    total = pass_count + dev_count

    if total > 0:
        pct = (pass_count / total) * 100
    else:
        pct = 0

    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total checks | {len(results)} |")
    lines.append(f"| PASS | {pass_count} |")
    lines.append(f"| DEVIATES | {dev_count} |")
    lines.append(f"| N/A | {na_count} |")
    lines.append(f"| Compliance rate | {pct:.1f}% |")
    lines.append("")

    # Per-model scorecard
    lines.append("## Per-Model Scorecard")
    lines.append("")

    # Get unique rules for header
    rules = sorted(set(r.rule for r in results))
    models = sorted(set(r.model for r in results))

    # Build lookup
    lookup: dict[tuple[str, str], RuleResult] = {}
    for r in results:
        lookup[(r.model, r.rule)] = r

    # Table header
    rule_short = [r.split(".")[-1] for r in rules]
    lines.append(f"| Model | {' | '.join(rule_short)} |")
    lines.append(f"|-------|{'|'.join(['---'] * len(rules))}|")

    for model in models:
        cells = []
        for rule_name in rules:
            r = lookup.get((model, rule_name))
            if r is None or r.result == Result.NA:
                cells.append("-")
            elif r.result == Result.PASS:
                cells.append("PASS")
            else:
                cells.append("**DEV**")
        lines.append(f"| {model} | {' | '.join(cells)} |")

    lines.append("")

    # Findings list
    deviations = [r for r in results if r.result == Result.DEVIATES]
    if deviations:
        lines.append("## Findings")
        lines.append("")
        for r in sorted(deviations, key=lambda x: (x.model, x.rule)):
            spec = f" (ref: `{r.spec_ref}`)" if r.spec_ref else ""
            lines.append(f"- **{r.model}** / `{r.rule}`: {r.finding}{spec}")
        lines.append("")
    else:
        lines.append("## Findings")
        lines.append("")
        lines.append("No deviations found. All models are spec-compliant.")
        lines.append("")

    return "\n".join(lines)
